apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: dask
  namespace: jhub
spec:
  idleTimeout: 3600
  scheduler:
    service:
      ports:
      - name: tcp-comm
        port: 8786
        nodePort: 31022
        protocol: TCP
        #targetPort: tcp-comm
        targetPort: 8786
      #- name: http-dashboard
      #  port: 8787
      #  protocol: TCP
      #  targetPort: http-dashboard
      #selector:
      #  dask.org/cluster-name: dask
      #  dask.org/component: scheduler
      selector:
        app.kubernetes.io/name: ssh-fwd
      #type: ClusterIP
      type: NodePort
    spec:
      containers:
      - args:
        - dask-scheduler
        - --host
        - 0.0.0.0
        env: []
        image: ghcr.io/icsc-spoke2-repo/jlab:wp5-alma9-highrate-v0.1.0
        livenessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 15
          periodSeconds: 20
        name: scheduler
        ports:
        - containerPort: 8786
          name: tcp-comm
          protocol: TCP
        - containerPort: 8787
          name: http-dashboard
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 0
          periodSeconds: 1
          timeoutSeconds: 300
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
      volumes:
      - name: cvmfs
        hostPath:
          path: /cvmfs-af-htcondor
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: vk-test
            
  worker:
    replicas: 0
    spec:
      containers:
      - args:
        - dask-worker
        - --name
        - $(DASK_WORKER_NAME)
        - --dashboard
        - --dashboard-address
        - "8788"
        env: []
        image: ghcr.io/icsc-spoke2-repo/jlab:wp5-alma9-highrate-v0.1.0
        name: worker
        ports:
        - containerPort: 8788
          name: http-dashboard
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
      volumes:
      - name: cvmfs
        hostPath:
          path: /cvmfs-af-htcondor
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: vk-test


