apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: dask
  namespace: jhub
spec:
  idleTimeout: 3600
  scheduler:
    service:
      ports:
      - name: tcp-comm
        port: 8912
        protocol: TCP
        targetPort: 8912
      - name: http-dashboard
        port: 8913
        protocol: TCP
        targetPort: 8913
      selector:
         app.kubernetes.io/name: ssh-fwd
    spec:
      containers:
      - args:
        - bash
        - -c
        - "'python3 /usr/local/bin/start_tunnel.py 8912 8913 & dask-scheduler --port 8912 --dashboard-address 8913'"
        env: 
        - name: USERNAME
          value: "YOUR USERNAME"
        - name: TOKEN
          value: "YOUR TOKEN"
        image: ghcr.io/ttedeschi/jlab:wp5-alma9-test-vk-6
        name: scheduler
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
      volumes:
      - name: cvmfs
        hostPath:
          path: /cvmfs-af-htcondor
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: vk-test
      tolerations:
      - key: virtual-node.interlink/no-schedule
        operator: Exists
      - key: virtual-kubelet.io/provider
        operator: Exists
            
  worker:
    replicas: 0
    spec:
      containers:
      - args:
        - dask-worker
        - --name
        - $(DASK_WORKER_NAME)
        - --dashboard
        - --dashboard-address
        - "8788"
        - --nthreads
        - "1"
        - --memory-limit
        - "2GB"
        env:
        - name: DASK_SCHEDULER_ADDRESS
          value: "tcp://localhost:8912"
        image: ghcr.io/ttedeschi/jlab:wp5-alma9-test-vk-6
        name: worker
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
      volumes:
      - name: cvmfs
        hostPath:
          path: /cvmfs-af-htcondor
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: vk-test
      tolerations:
      - key: virtual-node.interlink/no-schedule
        operator: Exists
      - key: virtual-kubelet.io/provider
        operator: Exists
